<a href="https://colab.research.google.com/github/mebre7/house-price-predictor-mlops/blob/colab_branch/notebooks/01_eda_and_baseline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploratory Data Analysis (EDA)
Exploratory Data Analysis (EDA) is a crucial step in the data analysis process that involves examining and visualizing data to uncover patterns, relationships, and insights. It helps in understanding the underlying structure of the data, identifying anomalies, and informing subsequent modeling decisions.

## 1. Load Data from PostgreSQL which is inside Supabase

In [1]:
from sqlalchemy import create_engine, text
import pandas as pd
import os
from dotenv import load_dotenv
from urllib.parse import quote_plus
from google.colab import userdata

ModuleNotFoundError: No module named 'google.colab'

In [4]:
DB_USER = userdata.get("SUPABASE_USER")
DB_PASSWORD = quote_plus(userdata.get("SUPABASE_PASSWORD"))
DB_HOST = userdata.get("SUPABASE_HOST")
DB_PORT = userdata.get("SUPABASE_PORT")
DB_NAME = userdata.get("SUPABASE_NAME")

# 2. Build SQLAlchemy connection string
DATABASE_URL = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine = create_engine(DATABASE_URL)
with engine.connect() as conn:
    df = pd.read_sql(
        text("SELECT * FROM housing_data"),
        conn
    )

df.head()

,Order,PID,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,...,Pool_Area,Pool_QC,Fence,Misc_Feature,Misc_Val,Mo_Sold,Yr_Sold,Sale_Type,Sale_Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,None,IR1,Lvl,...,0,None,None,None,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,None,Reg,Lvl,...,0,None,MnPrv,None,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,None,IR1,Lvl,...,0,None,None,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,None,Reg,Lvl,...,0,None,None,None,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,None,IR1,Lvl,...,0,None,MnPrv,None,0,3,2010,WD,Normal,189900

### Import packages

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

## 2. Basic Shape & Types Audit

In [5]:
df.shape

(2930, 82)

-> $2930$ rows and $82$ features/columns

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS_SubClass      2930 non-null   int64
 3   MS_Zoning        2930 non-null   object
 4   Lot_Frontage     2440 non-null   float64
 5   Lot_Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Alley            198 non-null    object
 8   Lot_Shape        2930 non-null   object
 9   Land_Contour     2930 non-null   object
 10  Utilities        2930 non-null   object
 11  Lot_Config       2930 non-null   object
 12  Land_Slope       2930 non-null   object
 13  Neighborhood     2930 non-null   object
 14  Condition_1      2930 non-null   object
 15  Condition_2      2930 non-null   object
 16  Bldg_Type        2930 non-null   object
 17  House_Style      2930 non-null   object
 18  Overall_Qual     2930 non-null   int64
 19  Overall_Cond     2930 non-null   int64
 20  Year_Built       2930 non-null   int64
 21  Year_Remod/Add   2930 non-null   int64
 22  Roof_Style       2930 non-null   object
 23  Roof_Matl        2930 non-null   object
 24  Exterior_1st     2930 non-null   object
 25  Exterior_2nd     2930 non-null   object
 26  Mas_Vnr_Type     1155 non-null   object
 27  Mas_Vnr_Area     2907 non-null   float64
 28  Exter_Qual       2930 non-null   object
 29  Exter_Cond       2930 non-null   object
 30  Foundation       2930 non-null   object
 31  Bsmt_Qual        2850 non-null   object
 32  Bsmt_Cond        2850 non-null   object
 33  Bsmt_Exposure    2847 non-null   object
 34  BsmtFin_Type_1   2850 non-null   object
 35  BsmtFin_SF_1     2929 non-null   float64
 36  BsmtFin_Type_2   2849 non-null   object
 37  BsmtFin_SF_2     2929 non-null   float64
 38  Bsmt_Unf_SF      2929 non-null   float64
 39  Total_Bsmt_SF    2929 non-null   float64
 40  Heating          2930 non-null   object
 41  Heating_QC       2930 non-null   object
 42  Central_Air      2930 non-null   object
 43  Electrical       2929 non-null   object
 44  1st_Flr_SF       2930 non-null   int64
 45  2nd_Flr_SF       2930 non-null   int64
 46  Low_Qual_Fin_SF  2930 non-null   int64
 47  Gr_Liv_Area      2930 non-null   int64
 48  Bsmt_Full_Bath   2928 non-null   float64
 49  Bsmt_Half_Bath   2928 non-null   float64
 50  Full_Bath        2930 non-null   int64
 51  Half_Bath        2930 non-null   int64
 52  Bedroom_AbvGr    2930 non-null   int64
 53  Kitchen_AbvGr    2930 non-null   int64
 54  Kitchen_Qual     2930 non-null   object
 55  TotRms_AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   object
 57  Fireplaces       2930 non-null   int64
 58  Fireplace_Qu     1508 non-null   object
 59  Garage_Type      2773 non-null   object
 60  Garage_Yr_Blt    2771 non-null   float64
 61  Garage_Finish    2771 non-null   object
 62  Garage_Cars      2929 non-null   float64
 63  Garage_Area      2929 non-null   float64
 64  Garage_Qual      2771 non-null   object
 65  Garage_Cond      2771 non-null   object
 66  Paved_Drive      2930 non-null   object
 67  Wood_Deck_SF     2930 non-null   int64
 68  Open_Porch_SF    2930 non-null   int64
 69  Enclosed_Porch   2930 non-null   int64
 70  3Ssn_Porch       2930 non-null   int64
 71  Screen_Porch     2930 non-null   int64
 72  Pool_Area        2930 non-null   int64
 73  Pool_QC          13 non-null     object
 74  Fence            572 non-null    object
 75  Misc_Feature     106 non-null    object
 76  Misc_Val         2930 non-null   int64
 77  Mo_Sold          2930 non-null   int64
 78  Yr_Sold          2930 non-null   int64
 79  Sale_Type        2930 non-null   object
 80  Sale_Condition   2930 non-null   object
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB

Of 82 columns:
- Float: 11
- Integer: 28
- Object (string): 43

In [7]:
df.dtypes

Order               int64
PID                 int64
MS_SubClass         int64
MS_Zoning          object
Lot_Frontage      float64
                   ...
Mo_Sold             int64
Yr_Sold             int64
Sale_Type          object
Sale_Condition     object
SalePrice           int64
Length: 82, dtype: object

In [18]:
df.describe()

,Order,PID,MS_SubClass,Lot_Frontage,Lot_Area,Overall_Qual,Overall_Cond,Year_Built,Year_Remod/Add,Mas_Vnr_Area,...,Wood_Deck_SF,Open_Porch_SF,Enclosed_Porch,3Ssn_Porch,Screen_Porch,Pool_Area,Misc_Val,Mo_Sold,Yr_Sold,SalePrice
count,2930.00000,2.930000e+03,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,...,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,1465.50000,7.144645e+08,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,...,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,845.96247,1.887308e+08,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,...,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,1.00000,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,733.25000,5.284770e+08,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,1465.50000,5.354536e+08,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,2197.75000,9.071811e+08,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,2930.00000,1.007100e+09,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

### Numerical and Categorical Columns

In [19]:
# define numerical & categorical columns
numerical_features = [feature for feature in df.columns if df[feature].dtype != 'O']
categorical_features = [feature for feature in df.columns if df[feature].dtype == 'O']

In [20]:
# print columns
print(f'{len(numerical_features)} numerical features: {numerical_features}')
print(f'\n{len(categorical_features)} categorical features: {categorical_features}')

39 numerical features: ['Order', 'PID', 'MS_SubClass', 'Lot_Frontage', 'Lot_Area', 'Overall_Qual', 'Overall_Cond', 'Year_Built', 'Year_Remod/Add', 'Mas_Vnr_Area', 'BsmtFin_SF_1', 'BsmtFin_SF_2', 'Bsmt_Unf_SF', 'Total_Bsmt_SF', '1st_Flr_SF', '2nd_Flr_SF', 'Low_Qual_Fin_SF', 'Gr_Liv_Area', 'Bsmt_Full_Bath', 'Bsmt_Half_Bath', 'Full_Bath', 'Half_Bath', 'Bedroom_AbvGr', 'Kitchen_AbvGr', 'TotRms_AbvGrd', 'Fireplaces', 'Garage_Yr_Blt', 'Garage_Cars', 'Garage_Area', 'Wood_Deck_SF', 'Open_Porch_SF', 'Enclosed_Porch', '3Ssn_Porch', 'Screen_Porch', 'Pool_Area', 'Misc_Val', 'Mo_Sold', 'Yr_Sold', 'SalePrice']

43 categorical features: ['MS_Zoning', 'Street', 'Alley', 'Lot_Shape', 'Land_Contour', 'Utilities', 'Lot_Config', 'Land_Slope', 'Neighborhood', 'Condition_1', 'Condition_2', 'Bldg_Type', 'House_Style', 'Roof_Style', 'Roof_Matl', 'Exterior_1st', 'Exterior_2nd', 'Mas_Vnr_Type', 'Exter_Qual', 'Exter_Cond', 'Foundation', 'Bsmt_Qual', 'Bsmt_Cond', 'Bsmt_Exposure', 'BsmtFin_Type_1', 'BsmtFin_Type_2', 'Heating', 'Heating_QC', 'Central_Air', 'Electrical', 'Kitchen_Qual', 'Functional', 'Fireplace_Qu', 'Garage_Type', 'Garage_Finish', 'Garage_Qual', 'Garage_Cond', 'Paved_Drive', 'Pool_QC', 'Fence', 'Misc_Feature', 'Sale_Type', 'Sale_Condition']

There are:
- **39** numeric features
- **43** categorical features

## 3. Missing Value Analysis

In [21]:
df.isnull().sum()

Order               0
PID                 0
MS_SubClass         0
MS_Zoning           0
Lot_Frontage      490
                 ...
Mo_Sold             0
Yr_Sold             0
Sale_Type           0
Sale_Condition      0
SalePrice           0
Length: 82, dtype: int64

#### Frequency of each column
- Proportion of individual values in each column

In [25]:
for col in categorical_features:
  print(df[col].value_counts(normalize=True) * 100)
  print(f"\n----------------------------------")

MS_Zoning
RL         77.576792
RM         15.767918
FV          4.744027
RH          0.921502
C (all)     0.853242
I (all)     0.068259
A (agr)     0.068259
Name: proportion, dtype: float64

----------------------------------
Street
Pave    99.590444
Grvl     0.409556
Name: proportion, dtype: float64

----------------------------------
Alley
Grvl    60.606061
Pave    39.393939
Name: proportion, dtype: float64

----------------------------------
Lot_Shape
Reg    63.447099
IR1    33.412969
IR2     2.593857
IR3     0.546075
Name: proportion, dtype: float64

----------------------------------
Land_Contour
Lvl    89.863481
HLS     4.095563
Bnk     3.993174
Low     2.047782
Name: proportion, dtype: float64

----------------------------------
Utilities
AllPub    99.897611
NoSewr     0.068259
NoSeWa     0.034130
Name: proportion, dtype: float64

----------------------------------
Lot_Config
Inside     73.037543
Corner     17.440273
CulDSac     6.143345
FR2         2.901024
FR3         0.477816
Name: proportion, dtype: float64

----------------------------------
Land_Slope
Gtl    95.187713
Mod     4.266212
Sev     0.546075
Name: proportion, dtype: float64

----------------------------------
Neighborhood
NAmes      15.119454
CollgCr     9.112628
OldTown     8.156997
Edwards     6.621160
Somerst     6.211604
NridgHt     5.665529
Gilbert     5.631399
Sawyer      5.153584
NWAmes      4.470990
SawyerW     4.266212
Mitchel     3.890785
BrkSide     3.686007
Crawfor     3.515358
IDOTRR      3.174061
Timber      2.457338
NoRidge     2.423208
StoneBr     1.740614
SWISU       1.638225
ClearCr     1.501706
MeadowV     1.262799
BrDale      1.023891
Blmngtn     0.955631
Veenker     0.819113
NPkVill     0.784983
Blueste     0.341297
Greens      0.273038
GrnHill     0.068259
Landmrk     0.034130
Name: proportion, dtype: float64

----------------------------------
Condition_1
Norm      86.075085
Feedr      5.597270
Artery     3.139932
RRAn       1.706485
PosN       1.331058
RRAe       0.955631
PosA       0.682594
RRNn       0.307167
RRNe       0.204778
Name: proportion, dtype: float64

----------------------------------
Condition_2
Norm      98.976109
Feedr      0.443686
Artery     0.170648
PosA       0.136519
PosN       0.136519
RRNn       0.068259
RRAe       0.034130
RRAn       0.034130
Name: proportion, dtype: float64

----------------------------------
Bldg_Type
1Fam      82.764505
TwnhsE     7.952218
Duplex     3.720137
Twnhs      3.447099
2fmCon     2.116041
Name: proportion, dtype: float64

----------------------------------
House_Style
1Story    50.546075
2Story    29.795222
1.5Fin    10.716724
SLvl       4.368601
SFoyer     2.832765
2.5Unf     0.819113
1.5Unf     0.648464
2.5Fin     0.273038
Name: proportion, dtype: float64

----------------------------------
Roof_Style
Gable      79.215017
Hip        18.805461
Gambrel     0.750853
Flat        0.682594
Mansard     0.375427
Shed        0.170648
Name: proportion, dtype: float64

----------------------------------
Roof_Matl
CompShg    98.532423
Tar&Grv     0.784983
WdShake     0.307167
WdShngl     0.238908
Membran     0.034130
ClyTile     0.034130
Roll        0.034130
Metal       0.034130
Name: proportion, dtype: float64

----------------------------------
Exterior_1st
VinylSd    35.017065
MetalSd    15.358362
HdBoard    15.085324
Wd Sdng    14.334471
Plywood     7.542662
CemntBd     4.300341
BrkFace     3.003413
WdShing     1.911263
AsbShng     1.501706
Stucco      1.467577
BrkComm     0.204778
AsphShn     0.068259
CBlock      0.068259
Stone       0.068259
PreCast     0.034130
ImStucc     0.034130
Name: proportion, dtype: float64

----------------------------------
Exterior_2nd
VinylSd    34.641638
MetalSd    15.255973
HdBoard    13.856655
Wd Sdng    13.549488
Plywood     9.351536
CmentBd     4.300341
Wd Shng     2.764505
BrkFace     1.604096
Stucco      1.604096
AsbShng     1.296928
Brk Cmn     0.750853
ImStucc     0.511945
Stone       0.204778
AsphShn     0.136519
CBlock      0.102389
PreCast     0.034130
Other       0.034130
Name: proportion, dtype: float64

----------------------------------
Mas_Vnr_Type
BrkFace    76.190476
Stone      21.558442
BrkCmn      2.164502
CBlock      0.086580
Name: proportion, dtype: float64

----------------------------------
Exter_Qual
TA    61.399317
Gd    33.754266
Ex     3.651877
Fa     1.194539
Name: proportion, dtype: float64

----------------------------------
Exter_Cond
TA    86.996587
Gd    10.204778
Fa     2.286689
Ex     0.409556
Po     0.102389
Name: proportion, dtype: float64

----------------------------------
Foundation
PConc     44.709898
CBlock    42.457338
BrkTil    10.614334
Slab       1.672355
Stone      0.375427
Wood       0.170648
Name: proportion, dtype: float64

----------------------------------
Bsmt_Qual
TA    45.017544
Gd    42.771930
Ex     9.052632
Fa     3.087719
Po     0.070175
Name: proportion, dtype: float64

----------------------------------
Bsmt_Cond
TA    91.789474
Gd     4.280702
Fa     3.649123
Po     0.175439
Ex     0.105263
Name: proportion, dtype: float64

----------------------------------
Bsmt_Exposure
No    66.947664
Av    14.682122
Gd     9.975413
Mn     8.394802
Name: proportion, dtype: float64

----------------------------------
BsmtFin_Type_1
GLQ    30.140351
Unf    29.859649
ALQ    15.052632
Rec    10.105263
BLQ     9.438596
LwQ     5.403509
Name: proportion, dtype: float64

----------------------------------
BsmtFin_Type_2
Unf    87.714988
Rec     3.720604
LwQ     3.123903
BLQ     2.386802
ALQ     1.860302
GLQ     1.193401
Name: proportion, dtype: float64

----------------------------------
Heating
GasA     98.464164
GasW      0.921502
Grav      0.307167
Wall      0.204778
OthW      0.068259
Floor     0.034130
Name: proportion, dtype: float64

----------------------------------
Heating_QC
Ex    51.023891
TA    29.488055
Gd    16.245734
Fa     3.139932
Po     0.102389
Name: proportion, dtype: float64

----------------------------------
Central_Air
Y    93.31058
N     6.68942
Name: proportion, dtype: float64

----------------------------------
Electrical
SBrkr    91.567088
FuseA     6.418573
FuseF     1.707067
FuseP     0.273131
Mix       0.034141
Name: proportion, dtype: float64

----------------------------------
Kitchen_Qual
TA    50.989761
Gd    39.590444
Ex     6.996587
Fa     2.389078
Po     0.034130
Name: proportion, dtype: float64

----------------------------------
Functional
Typ     93.105802
Min2     2.389078
Min1     2.218430
Mod      1.194539
Maj1     0.648464
Maj2     0.307167
Sev      0.068259
Sal      0.068259
Name: proportion, dtype: float64

----------------------------------
Fireplace_Qu
Gd    49.336870
TA    39.787798
Fa     4.973475
Po     3.050398
Ex     2.851459
Name: proportion, dtype: float64

----------------------------------
Garage_Type
Attchd     62.423368
Detchd     28.200505
BuiltIn     6.707537
Basment     1.298233
2Types      0.829427
CarPort     0.540930
Name: proportion, dtype: float64

----------------------------------
Garage_Finish
Unf    44.424396
RFn    29.303501
Fin    26.272104
Name: proportion, dtype: float64

----------------------------------
Garage_Qual
TA    94.370263
Fa     4.474919
Gd     0.866113
Po     0.180440
Ex     0.108264
Name: proportion, dtype: float64

----------------------------------
Garage_Cond
TA    96.174666
Fa     2.670516
Gd     0.541321
Po     0.505233
Ex     0.108264
Name: proportion, dtype: float64

----------------------------------
Paved_Drive
Y    90.511945
N     7.372014
P     2.116041
Name: proportion, dtype: float64

----------------------------------
Pool_QC
Ex    30.769231
Gd    30.769231
TA    23.076923
Fa    15.384615
Name: proportion, dtype: float64

----------------------------------
Fence
MnPrv    57.692308
GdPrv    20.629371
GdWo     19.580420
MnWw      2.097902
Name: proportion, dtype: float64

----------------------------------
Misc_Feature
Shed    89.622642
Gar2     4.716981
Othr     3.773585
Elev     0.943396
TenC     0.943396
Name: proportion, dtype: float64

----------------------------------
Sale_Type
WD       86.552901
New       8.156997
COD       2.969283
ConLD     0.887372
CWD       0.409556
ConLI     0.307167
ConLw     0.273038
Oth       0.238908
Con       0.170648
VWD       0.034130
Name: proportion, dtype: float64

----------------------------------
Sale_Condition
Normal     82.354949
Partial     8.361775
Abnorml     6.484642
Family      1.569966
Alloca      0.819113
AdjLand     0.409556
Name: proportion, dtype: float64

----------------------------------