<a href="https://colab.research.google.com/github/mebre7/house-price-predictor-mlops/blob/colab_branch/notebooks/02_feature_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Feature Engineering
Feature engineering is the process of using domain knowledge to create new features from existing data. It involves transforming raw data into a format that is more suitable for machine learning algorithms, which can lead to improved model performance.
- In this notebook of the house price predictor project, I will be performing feature engineering on the dataset to create new features that can help improve the predictive power of the model. This may include creating interaction terms, polynomial features, or aggregating existing features to capture more complex relationships in the data.

## Data loading

In [37]:
from sqlalchemy import create_engine, text
import pandas as pd
from urllib.parse import quote_plus
from google.colab import userdata

In [38]:
DB_USER = userdata.get("SUPABASE_USER")
DB_PASSWORD = quote_plus(userdata.get("SUPABASE_PASSWORD"))
DB_HOST = userdata.get("SUPABASE_HOST")
DB_PORT = userdata.get("SUPABASE_PORT")
DB_NAME = userdata.get("SUPABASE_NAME")

# 2. Build SQLAlchemy connection string
DATABASE_URL = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine = create_engine(DATABASE_URL)
with engine.connect() as conn:
    df = pd.read_sql(
        text("SELECT * FROM housing_data"),
        conn
    )

df.head()

,Order,PID,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,...,Pool_Area,Pool_QC,Fence,Misc_Feature,Misc_Val,Mo_Sold,Yr_Sold,Sale_Type,Sale_Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,None,IR1,Lvl,...,0,None,None,None,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,None,Reg,Lvl,...,0,None,MnPrv,None,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,None,IR1,Lvl,...,0,None,None,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,None,Reg,Lvl,...,0,None,None,None,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,None,IR1,Lvl,...,0,None,MnPrv,None,0,3,2010,WD,Normal,189900

In [39]:
df = df.drop(columns=["Order", "PID"])

In [40]:
df.head()

,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,Lot_Config,...,Pool_Area,Pool_QC,Fence,Misc_Feature,Misc_Val,Mo_Sold,Yr_Sold,Sale_Type,Sale_Condition,SalePrice
0,20,RL,141.0,31770,Pave,None,IR1,Lvl,AllPub,Corner,...,0,None,None,None,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,MnPrv,None,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,Pave,None,IR1,Lvl,AllPub,Corner,...,0,None,None,Gar2,12500,6,2010,WD,Normal,172000
3,20,RL,93.0,11160,Pave,None,Reg,Lvl,AllPub,Corner,...,0,None,None,None,0,4,2010,WD,Normal,244000
4,60,RL,74.0,13830,Pave,None,IR1,Lvl,AllPub,Inside,...,0,None,MnPrv,None,0,3,2010,WD,Normal,189900

## Import Packages

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

## 1. Outlier Removal

## 2. Train-Test split

In [42]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=["SalePrice"])
y = df["SalePrice"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [43]:
X_train.head()

,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,Lot_Config,...,Screen_Porch,Pool_Area,Pool_QC,Fence,Misc_Feature,Misc_Val,Mo_Sold,Yr_Sold,Sale_Type,Sale_Condition
381,20,RL,80.0,10400,Pave,None,Reg,Lvl,AllPub,Inside,...,0,0,None,MnPrv,None,0,6,2009,WD,Family
834,60,RL,NaN,28698,Pave,None,IR2,Low,AllPub,CulDSac,...,225,0,None,None,None,0,6,2009,WD,Abnorml
1898,20,RL,75.0,7388,Pave,None,Reg,Lvl,AllPub,Corner,...,0,0,None,None,None,0,7,2007,WD,Normal
678,90,RL,60.0,8544,Pave,None,Reg,Lvl,AllPub,Corner,...,0,0,None,None,None,0,6,2009,WD,Normal
700,70,RM,57.0,6406,Pave,Grvl,Reg,Lvl,AllPub,Inside,...,182,0,None,MnPrv,None,0,10,2009,WD,Normal

In [44]:
X_test.head()

,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,Lot_Config,...,Screen_Porch,Pool_Area,Pool_QC,Fence,Misc_Feature,Misc_Val,Mo_Sold,Yr_Sold,Sale_Type,Sale_Condition
1357,50,RL,60.0,9144,Pave,Pave,Reg,Lvl,AllPub,Inside,...,0,0,None,None,None,0,3,2008,WD,Normal
2367,160,RM,21.0,1953,Pave,None,Reg,Lvl,AllPub,Inside,...,0,0,None,None,None,0,6,2006,WD,Normal
2822,20,RL,73.0,16133,Pave,None,Reg,HLS,AllPub,Inside,...,112,0,None,None,None,0,12,2006,WD,Abnorml
2126,20,RL,70.0,16561,Pave,None,IR2,Low,AllPub,Inside,...,0,0,None,GdPrv,None,0,7,2007,WD,Normal
1544,160,RM,24.0,1950,Pave,None,Reg,Lvl,AllPub,Inside,...,0,0,None,GdPrv,None,0,7,2008,COD,Normal

In [45]:
y_train.head()

381     152000
834     185000
1898    150750
678      92900
700     150000
Name: SalePrice, dtype: int64

In [46]:
y_test.head()

1357    162500
2367     83000
2822    119900
2126    147900
1544    151000
Name: SalePrice, dtype: int64

## 3. Missing Value Handling (Imputation)

In [47]:
count = df.isnull().sum().sort_values(ascending=False)
percentage = ((df.isnull().sum() / df.isnull().count()) * 100).sort_values(ascending=False)
null_values = pd.concat([count, percentage], axis=1, keys=['Count', 'Percentage'])

In [48]:
null_values.head()

              Count  Percentage
Pool_QC        2917   99.556314
Misc_Feature   2824   96.382253
Alley          2732   93.242321
Fence          2358   80.477816
Mas_Vnr_Type   1775   60.580205

In [69]:
df.columns.to_list()

['MS_SubClass',
 'MS_Zoning',
 'Lot_Frontage',
 'Lot_Area',
 'Street',
 'Alley',
 'Lot_Shape',
 'Land_Contour',
 'Utilities',
 'Lot_Config',
 'Land_Slope',
 'Neighborhood',
 'Condition_1',
 'Condition_2',
 'Bldg_Type',
 'House_Style',
 'Overall_Qual',
 'Overall_Cond',
 'Year_Built',
 'Year_Remod/Add',
 'Roof_Style',
 'Roof_Matl',
 'Exterior_1st',
 'Exterior_2nd',
 'Mas_Vnr_Type',
 'Mas_Vnr_Area',
 'Exter_Qual',
 'Exter_Cond',
 'Foundation',
 'Bsmt_Qual',
 'Bsmt_Cond',
 'Bsmt_Exposure',
 'BsmtFin_Type_1',
 'BsmtFin_SF_1',
 'BsmtFin_Type_2',
 'BsmtFin_SF_2',
 'Bsmt_Unf_SF',
 'Total_Bsmt_SF',
 'Heating',
 'Heating_QC',
 'Central_Air',
 'Electrical',
 '1st_Flr_SF',
 '2nd_Flr_SF',
 'Low_Qual_Fin_SF',
 'Gr_Liv_Area',
 'Bsmt_Full_Bath',
 'Bsmt_Half_Bath',
 'Full_Bath',
 'Half_Bath',
 'Bedroom_AbvGr',
 'Kitchen_AbvGr',
 'Kitchen_Qual',
 'TotRms_AbvGrd',
 'Functional',
 'Fireplaces',
 'Fireplace_Qu',
 'Garage_Type',
 'Garage_Yr_Blt',
 'Garage_Finish',
 'Garage_Cars',
 'Garage_Area',
 'Garage_Qual',
 'Garage_Cond',
 'Paved_Drive',
 'Wood_Deck_SF',
 'Open_Porch_SF',
 'Enclosed_Porch',
 '3Ssn_Porch',
 'Screen_Porch',
 'Pool_Area',
 'Pool_QC',
 'Fence',
 'Misc_Feature',
 'Misc_Val',
 'Mo_Sold',
 'Yr_Sold',
 'Sale_Type',
 'Sale_Condition',
 'SalePrice']

**Visualize missing values**

In [59]:
fig = px.bar(x=missing.index, y=missing.values,
             labels={'x': 'Features', 'y': 'Percent of missing values'},
             title='Percent missing data by feature')
fig.update_layout(xaxis_tickangle=-45)
fig.show()

**Structural Absence (Replace `NaN` with `None` or `0`)**

These columns use missing values to denote that the feature does not exist on the property.

**`structural_categorical` (Fill with "None")**

In [73]:
structural_categorical = [
    'Alley', 'Mas_Vnr_Type', 'Bsmt_Qual', 'Bsmt_Cond', 'Bsmt_Exposure',
    'BsmtFin_Type_1', 'BsmtFin_Type_2', 'Fireplace_Qu', 'Garage_Type',
    'Garage_Finish', 'Garage_Qual', 'Garage_Cond', 'Pool_QC', 'Fence', 'Misc_Feature'
]

In [82]:
df.Alley=["No Alley" if x is np.nan else x for x in df.Alley]
df.Mas_Vnr_Type=["Missing" if x is np.nan else x for x in df.Mas_Vnr_Type]
df.Bsmt_Qual=["No Bsmnt" if x is np.nan else x for x in df.Bsmt_Qual]
df.Bsmt_Cond=["No Bsmnt" if x is np.nan else x for x in df.Bsmt_Cond]
df.Bsmt_Exposure=["No Bsmnt" if x is np.nan else x for x in df.Bsmt_Exposure]
df.BsmtFin_Type_1=["No Bsmnt" if x is np.nan else x for x in df.BsmtFin_Type_1]
df.BsmtFin_Type_2=["No Bsmnt" if x is np.nan else x for x in df.BsmtFin_Type_2]
df.Fireplace_Qu=["No Firepl" if x is np.nan else x for x in df.Fireplace_Qu]
df.Garage_Type=["No Grg" if x is np.nan else x for x in df.Garage_Type]
df.Garage_Finish=["No Grg" if x is np.nan else x for x in df.Garage_Finish]
df.Garage_Qual=["No Grg" if x is np.nan else x for x in df.Garage_Qual]
df.Garage_Cond=["No Grg" if x is np.nan else x for x in df.Garage_Cond]
df.Pool_QC=["No Pool" if x is np.nan else x for x in df.Pool_QC]
df.Fence=["No Fence" if x is np.nan else x for x in df.Fence]
df.Misc_Feature=["None" if x is np.nan else x for x in df.Misc_Feature]

In [83]:
df[structural_categorical]

,Alley,Mas_Vnr_Type,Bsmt_Qual,Bsmt_Cond,Bsmt_Exposure,BsmtFin_Type_1,BsmtFin_Type_2,Fireplace_Qu,Garage_Type,Garage_Finish,Garage_Qual,Garage_Cond,Pool_QC,Fence,Misc_Feature
0,None,Stone,TA,Gd,Gd,BLQ,Unf,Gd,Attchd,Fin,TA,TA,None,None,None
1,None,None,TA,TA,No,Rec,LwQ,None,Attchd,Unf,TA,TA,None,MnPrv,None
2,None,BrkFace,TA,TA,No,ALQ,Unf,None,Attchd,Unf,TA,TA,None,None,Gar2
3,None,None,TA,TA,No,ALQ,Unf,TA,Attchd,Fin,TA,TA,None,None,None
4,None,None,Gd,TA,No,GLQ,Unf,TA,Attchd,Fin,TA,TA,None,MnPrv,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,None,None,TA,TA,Av,GLQ,Unf,None,Detchd,Unf,TA,TA,None,GdPrv,None
2926,None,None,Gd,TA,Av,BLQ,ALQ,None,Attchd,Unf,TA,TA,None,MnPrv,None
2927,None,None,Gd,TA,Av,GLQ,Unf,None,None,None,None,None,None,MnPrv,Shed
2928,None,None,Gd,TA,Av,ALQ,LwQ,TA,Attchd,RFn,TA,TA,None,None,None
2929,None,BrkFace,Gd,TA,Av,LwQ,Unf,TA,Attchd,Fin,TA,TA,None,None,None

**structural_numerical (Fill with 0)**

In [72]:
structural_numerical = [
    'Mas_Vnr_Area', 'BsmtFin_SF_1', 'BsmtFin_SF_2', 'Bsmt_Unf_SF', 'Total_Bsmt_SF',
    'Bsmt_Full_Bath', 'Bsmt_Half_Bath', 'Garage_Cars', 'Garage_Area'
]

In [71]:
len(structural_categorical)

15

## 4. Feature Creation / Engineering (Added Step)

## 5. Mathematical Transformation

## 6. Categorical Encoding

## 7. Scaling

## 8. Pipeline and ColumnTransformer

## 9. Modeling (Training)